from enum import Enum


class SpaceType(str, Enum):
    # Rooms
    ROOM_GENERIC = "ROOM_GENERIC"
    ROOM_OFFICE = "ROOM_OFFICE"
    ROOM_CLASSROOM = "ROOM_CLASSROOM"
    ROOM_LECTURE_HALL = "ROOM_LECTURE_HALL"
    ROOM_LAB = "ROOM_LAB"
    ROOM_MEETING = "ROOM_MEETING"
    ROOM_STORAGE = "ROOM_STORAGE"
    ROOM_UTILITY = "ROOM_UTILITY"
    RESTROOM = "RESTROOM"
    RESTROOM_ACCESSIBLE = "RESTROOM_ACCESSIBLE"
    # Horizontal circulation
    CORRIDOR = "CORRIDOR"
    CORRIDOR_SEGMENT = "CORRIDOR_SEGMENT"
    LOBBY = "LOBBY"
    WAITING_AREA = "WAITING_AREA"
    RECEPTION = "RECEPTION"
    # Entrances/exits
    ENTRANCE = "ENTRANCE"
    ENTRANCE_SECONDARY = "ENTRANCE_SECONDARY"
    EXIT_EMERGENCY = "EXIT_EMERGENCY"
    # Vertical circulation
    STAIRCASE = "STAIRCASE"
    ELEVATOR = "ELEVATOR"
    ESCALATOR = "ESCALATOR"
    RAMP = "RAMP"
    # Cross-building connectors
    BRIDGE = "BRIDGE"
    TUNNEL = "TUNNEL"
    COVERED_WALKWAY = "COVERED_WALKWAY"
    # Outdoor
    OUTDOOR_PATH = "OUTDOOR_PATH"
    OUTDOOR_PLAZA = "OUTDOOR_PLAZA"
    OUTDOOR_COURTYARD = "OUTDOOR_COURTYARD"
    OUTDOOR_STAIRS = "OUTDOOR_STAIRS"
    PARKING = "PARKING"
    # Amenities
    CAFETERIA = "CAFETERIA"
    CAFE = "CAFE"
    LIBRARY = "LIBRARY"
    GYM = "GYM"
    AUDITORIUM = "AUDITORIUM"
    SHOP = "SHOP"
    # Connections (intermediate door/passage nodes)
    DOOR_STANDARD = "DOOR_STANDARD"
    DOOR_AUTOMATIC = "DOOR_AUTOMATIC"
    DOOR_LOCKED = "DOOR_LOCKED"
    DOOR_EMERGENCY = "DOOR_EMERGENCY"
    PASSAGE = "PASSAGE"
    OPEN = "OPEN"
    # Special
    INACCESSIBLE = "INACCESSIBLE"
    UNKNOWN = "UNKNOWN"


# Subset: connection/door node types
CONN_SPACE_TYPES = {
    SpaceType.DOOR_STANDARD,
    SpaceType.DOOR_AUTOMATIC,
    SpaceType.DOOR_LOCKED,
    SpaceType.DOOR_EMERGENCY,
    SpaceType.PASSAGE,
    SpaceType.OPEN,
    SpaceType.STAIRCASE,
    SpaceType.ELEVATOR,
    SpaceType.ESCALATOR,
    SpaceType.RAMP,
}

# Subset: room types (for room-specific queries)
ROOM_SPACE_TYPES = {
    SpaceType.ROOM_GENERIC,
    SpaceType.ROOM_OFFICE,
    SpaceType.ROOM_CLASSROOM,
    SpaceType.ROOM_LECTURE_HALL,
    SpaceType.ROOM_LAB,
    SpaceType.ROOM_MEETING,
    SpaceType.ROOM_STORAGE,
    SpaceType.ROOM_UTILITY,
    SpaceType.RESTROOM,
    SpaceType.RESTROOM_ACCESSIBLE,
}
